### PR TITLE
Add cypress javascript runner

### PR DESCRIPTION
**Pull request by megalithic**
Make sure these boxes are checked before submitting your pull request:

- [x] Add fixtures and spec when implementing or updating a test runner
- [x] Update the README accordingly
- [x] Update the Vim documentation in `doc/test.txt`

### CODE REVIEW

**Comment by megalithic** [comment]
@codeinabox let me know if there's anything i need to update/change/add/etc. thanks!

**Comment by codeinabox** [comment]
> @codeinabox let me know if there's anything i need to update/change/add/etc. thanks!

Thanks, if you could apply the changes to the README without unnecessary reformatting I am happy to approve and merge this

**Comment by megalithic** [comment]
@codeinabox done! thank you!

**Comment by megalithic** [comment]
@codeinabox thanks to you and @janko both for making it easy to contribute and for such an incredibly valuable project! Cheers!

**Pull request merged**
