### PR TITLE
Add runner for dhruvasagar/vim-testify

### PR DESCRIPTION
**Pull request by dhruvasagar**
Hi,

I built a small unit testing plugin which works for me. Just wanted to add a runner for this so I followed suit based on the existing plugins for viml. I notice there is no documentation for the existing plugins in either the README or the doc/test.txt so I haven't added anything yet. I also do not see specs for any runners (I might not be looking in the right place, do point some out to me).

Let me know what you think or if any further changes are required.

- [x] Add fixtures and spec when implementing or updating a test runner
- [x] Update the README accordingly
- [x] Update the Vim documentation in `doc/test.txt`

### CODE REVIEW

**Comment by codeinabox** [comment]
Thank you for this pull request, very much appreciated. For an example of updating the documentation and adding specs for your runner please refer to this https://github.com/janko/vim-test/pull/409

**Comment by dhruvasagar** [comment]
@codeinabox Thanks, I have added specs & updated documentation

**Comment by codeinabox** [comment]
Looks good, only thing missing is updating doc/test.txt

**Comment by dhruvasagar** [comment]
@codeinabox Not sure what to add there, there's no command since there's no executable for vim-testify, tests are run within vim itself.

**Comment by codeinabox** [comment]
Oh I see. This looks good to me but I'll leave it with @janko for final approval

**Comment by dhruvasagar** [comment]
What's keeping this from getting merged ? Let me guys, thanks

**Comment by codeinabox** [comment]
Thank you again for the pull request, very much appreciated!

**Pull request merged**
